# ARRAY AXIS SUMMATIONS (3X3)

This code will generate a 3X3 array with random numbers and will compute the sum of the array’s elements along different axes.

### **Function Definitions**

- **`axisSummation(arr, axis)`**:
  - This function sums the elements of the array `arr`.
  - If `axis=None`, it sums all elements.
  - If `axis=0`, it sums each column.
  - If `axis=1`, it sums each row.

### **Timing the Summations**

The code uses Python’s `timeit` module to measure how long it takes to:

- Sum all elements of the array.
- Sum the rows of the array.
- Sum the columns of the array.

Each summation is repeated 1,000 times to measure performance.

In [1]:
import numpy as np
import timeit as tm

# Function to sum the array elements along the specified axis
def axisSummation(arr, axis=None):
    """
    Computes the sum of array elements along a specified axis.
    
    Parameters:
    arr (ndarray): The input array.
    axis (int, optional): The axis along which the summation is performed. 
                          If None, sums over the entire array.
    
    Returns:
    float or ndarray: The sum of the array elements along the specified axis.
    """
    return np.sum(arr, axis=axis)

# Generate a 3x3 array with random numbers
arr = np.random.rand(3, 3)

# Define functions to time the summation for rows and columns
def sum_array():
    """
    Computes the sum of all elements in the array.
    
    Returns:
    float: The sum of all elements in the array.
    """
    return axisSummation(arr, axis=None) # Summing all elements in the array

def sum_rows():
    """
    Computes the sum of elements along each row of the array.
    
    Returns:
    ndarray: The sum of each row in the array.
    """
    return axisSummation(arr, axis=1)  # Summing along rows (axis=1)

def sum_columns():
    """
    Computes the sum of elements along each column of the array.
    
    Returns:
    ndarray: The sum of each column in the array.
    """
    return axisSummation(arr, axis=0)  # Summing along columns (axis=0)

# Print the array
print("Array:\n", arr)

# Record the time to sum the entire array, rows, and columns
time_array = tm.timeit(lambda: sum_array, number=1000)  # Sum array 1000 times
time_rows = tm.timeit(lambda: sum_rows, number=1000)  # Sum rows 1000 times
time_columns = tm.timeit(lambda: sum_columns, number=1000)  # Sum columns 1000 times

# Display results
print("\nSum of array:", sum_array())
print("Time taken to sum every element in the array (1000 runs):", time_array, "seconds")

print("\nSum of rows:", sum_rows())
print("Time taken to sum rows (1000 runs):", time_rows, "seconds")

print("\nSum of columns:", sum_columns())
print("Time taken to sum columns (1000 runs):", time_columns, "seconds")




Array:
 [[0.6136588  0.62364872 0.97219813]
 [0.83698582 0.01584874 0.28342473]
 [0.32181469 0.87595252 0.61141962]]

Sum of array: 5.154951778746187
Time taken to sum every element in the array (1000 runs): 1.9300030544400215e-05 seconds

Sum of rows: [2.20950565 1.1362593  1.80918683]
Time taken to sum rows (1000 runs): 1.910002902150154e-05 seconds

Sum of columns: [1.77245931 1.51544999 1.86704248]
Time taken to sum columns (1000 runs): 1.910002902150154e-05 seconds


# ARRAY AXIS SUMMATION (100x100 RANDOM NUMBERS)

We will now use a 100X100 array instead of a 3X3 and see if we get significant differences in the results.

In [5]:
import numpy as np
import timeit as tm

# Function to sum the array elements along the specified axis
def axisSummation(arr, axis=None):
    """
    Computes the sum of array elements along a specified axis.
    
    Parameters:
    arr (ndarray): The input array.
    axis (int, optional): The axis along which the summation is performed. 
                          If None, sums over the entire array.
    
    Returns:
    float or ndarray: The sum of the array elements along the specified axis.
    """
    return np.sum(arr, axis=axis)

# Generate a 100x100 array with random numbers
arr = np.random.rand(100, 100)

# Define functions to time the summation for rows and columns
def sum_array():
    """
    Computes the sum of all elements in the array.
    
    Returns:
    float: The sum of all elements in the array.
    """
    return axisSummation(arr, axis=None)  # Summing all elements in the array

def sum_rows():
    """
    Computes the sum of elements along each row of the array.
    
    Returns:
    ndarray: The sum of each row in the array.
    """
    return axisSummation(arr, axis=1)  # Summing along rows (axis=1)

def sum_columns():
    """
    Computes the sum of elements along each column of the array.
    
    Returns:
    ndarray: The sum of each column in the array.
    """
    return axisSummation(arr, axis=0)  # Summing along columns (axis=0)

# Print the array
print("Array:\n", arr)

# Record the time to sum the entire array, rows, and columns
time_array = tm.timeit(lambda: sum_array, number=1000)  # Sum array 1000 times
time_rows = tm.timeit(lambda: sum_rows, number=1000)  # Sum rows 1000 times
time_columns = tm.timeit(lambda: sum_columns, number=1000)  # Sum columns 1000 times

# Display results
print("\nSum of array:", sum_array())
print("Time taken to sum every element in the array (1000 runs):", time_array, "seconds")

print("Time taken to sum rows (1000 runs):", time_rows, "seconds")

print("Time taken to sum columns (1000 runs):", time_columns, "seconds")



Array:
 [[0.73804701 0.21665273 0.58662005 ... 0.25686384 0.49014221 0.46432597]
 [0.88570391 0.52115395 0.56148895 ... 0.41114459 0.38641685 0.72566564]
 [0.58198277 0.10733035 0.06575349 ... 0.24194326 0.24600741 0.52096315]
 ...
 [0.07212317 0.7419552  0.51022731 ... 0.49552381 0.95094121 0.49103792]
 [0.01685729 0.00144424 0.03150865 ... 0.18471095 0.13047048 0.32381033]
 [0.41361662 0.22661972 0.54165543 ... 0.19938478 0.13017642 0.49503951]]

Sum of array: 4985.49707709499
Time taken to sum every element in the array (1000 runs): 1.9600032828748226e-05 seconds
Time taken to sum rows (1000 runs): 1.9200029782950878e-05 seconds
Time taken to sum columns (1000 runs): 1.9200029782950878e-05 seconds


# ARRAY AXIS SUMMATION (100X100 RANDOM NUMBERS) USING EINSTEIN NOTATION

Now we will use einstein notation to compute the summ of the various axis in the 100X100 array.

In [6]:
import numpy as np
import timeit as tm

# Function to sum the array elements along the specified axis using Einstein summation notation
def axisSummation(arr, axis=None):
    if axis is None:  # Sum all elements
        return np.einsum('ij->', arr)  # Summing over all indices
    elif axis == 0:  # Sum over columns
        return np.einsum('ij->j', arr)  # Summing over rows (result is a sum over columns)
    elif axis == 1:  # Sum over rows
        return np.einsum('ij->i', arr)  # Summing over columns (result is a sum over rows)

# Generate a 100x100 array with random numbers
arr = np.random.rand(100, 100)

# Define functions to time the summation for rows and columns
def sum_array():
    return axisSummation(arr, axis=None) # Summing all elements in the array

def sum_rows():
    return axisSummation(arr, axis=1)  # Summing along rows

def sum_columns():
    return axisSummation(arr, axis=0)  # Summing along columns

# Print the array
print("Array:\n", arr)

# Record the time to sum rows and columns
time_array = tm.timeit(lambda: sum_array, number=1000)  # Sum array 1000 times
time_rows = tm.timeit(lambda: sum_rows, number=1000)  # Sum rows 1000 times
time_columns = tm.timeit(lambda: sum_columns, number=1000)  # Sum columns 1000 times

# Display resultsimport numpy as np
import timeit as tm

# Function to sum the array elements along the specified axis using Einstein summation notation
def axisSummation(arr, axis=None):
    """
    Computes the sum of array elements using Einstein summation notation.
    
    Parameters:
    arr (ndarray): The input 2D array.
    axis (int, optional): The axis along which the summation is performed.
                          If None, sums over all elements in the array.
                          axis=0 sums over columns, axis=1 sums over rows.
    
    Returns:
    float or ndarray: The sum of the array elements along the specified axis.
                      If axis=None, a scalar sum of all elements is returned.
                      If axis=0, returns the sum over columns.
                      If axis=1, returns the sum over rows.
    """
    if axis is None:  # Sum all elements
        return np.einsum('ij->', arr)  # Summing over all indices
    elif axis == 0:  # Sum over columns
        return np.einsum('ij->j', arr)  # Summing over rows (result is a sum over columns)
    elif axis == 1:  # Sum over rows
        return np.einsum('ij->i', arr)  # Summing over columns (result is a sum over rows)

# Generate a 100x100 array with random numbers
arr = np.random.rand(100, 100)

# Define functions to time the summation for rows and columns
def sum_array():
    """
    Computes the sum of all elements in the array using Einstein summation notation.
    
    Returns:
    float: The sum of all elements in the array.
    """
    return axisSummation(arr, axis=None)  # Summing all elements in the array

def sum_rows():
    """
    Computes the sum of elements along each row of the array using Einstein summation notation.
    
    Returns:
    ndarray: The sum of each row in the array.
    """
    return axisSummation(arr, axis=1)  # Summing along rows

def sum_columns():
    """
    Computes the sum of elements along each column of the array using Einstein summation notation.
    
    Returns:
    ndarray: The sum of each column in the array.
    """
    return axisSummation(arr, axis=0)  # Summing along columns

# Print the array
print("Array:\n", arr)

# Record the time to sum the entire array, rows, and columns
time_array = tm.timeit(lambda: sum_array, number=1000)  # Sum array 1000 times
time_rows = tm.timeit(lambda: sum_rows, number=1000)  # Sum rows 1000 times
time_columns = tm.timeit(lambda: sum_columns, number=1000)  # Sum columns 1000 times

# Display results
print("\nSum of array:", sum_array())
print("Time taken to sum every element in the array (1000 runs):", time_array, "seconds")

print("Time taken to sum rows (1000 runs):", time_rows, "seconds")

print("Time taken to sum columns (1000 runs):", time_columns, "seconds")


Array:
 [[0.11607543 0.45352695 0.77446888 ... 0.91334422 0.64981935 0.71422528]
 [0.61916917 0.99917523 0.48188582 ... 0.26813604 0.0349898  0.067763  ]
 [0.95644114 0.88784654 0.77344803 ... 0.61883285 0.7357471  0.11576712]
 ...
 [0.81504173 0.87028966 0.44490791 ... 0.03868336 0.14040099 0.7651616 ]
 [0.31085781 0.42252864 0.44890679 ... 0.83329817 0.19198444 0.99638875]
 [0.88579417 0.68230521 0.29905683 ... 0.42034654 0.16945231 0.67225019]]
Array:
 [[0.38301321 0.62802476 0.3872929  ... 0.56697225 0.9697771  0.85224634]
 [0.88719569 0.2243229  0.60786485 ... 0.5852214  0.83253073 0.98142808]
 [0.62629239 0.22963051 0.81268867 ... 0.18989476 0.92087688 0.58225196]
 ...
 [0.00486952 0.47559388 0.57572367 ... 0.03613656 0.19130278 0.82695679]
 [0.74638549 0.44000006 0.099807   ... 0.64343743 0.18949385 0.64613042]
 [0.95428633 0.6327909  0.96246937 ... 0.01791778 0.43134907 0.27696669]]

Sum of array: 5033.307416941125
Time taken to sum every element in the array (1000 runs): 1.980